default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: micro-rails_development
test:
  <<: *default
  database: micro-rails_test
production:
  <<: *default
  database: micro-rails_production
  username: micro-rails
  password: <%= ENV['MICRO-RAILS_DATABASE_PASSWORD'] %>
